### ISSUE TITLE
`wwctl overlay edit` command creates new files with 0600 permissions instead of defaults

### ISSUE THREAD

**Issue by conxuro** [warewulf/warewulf#1416]
### Steps to reproduce

```
[root@hpcmaster testoverlay]# umask
0022
[root@hpcmaster testoverlay]# wwctl overlay edit testoverlay testdir/testfile --parents
[root@hpcmaster testoverlay]# ls -la testdir
total 0
drwxr-xr-x 2 root root 22 sep 25 10:29 .
drwxr-xr-x 4 root root 32 sep 25 10:29 ..
-rw------- 1 root root  0 sep 25 10:29 testfile
```

### Error message

No errors reported, but permissions are set to 600 in spite of the umask. Directories are set to 755 instead.

### Information on your system

```
[root@hpcmaster ~]# wwctl version                                       
wwctl version:   4.5.6-1                                                
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.6-1" 
```
```
[root@hpcmaster ~]# cat /etc/os-release                           
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10" 
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Thanks for the report, @conxuro. We've had some trouble with umasks recently; probably just got our wires crossed somewhere.

**Comment by jleister** [comment]
root@hpc ~ ✾ wwctl version
wwctl version:	 4.6.1-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.6.1-1"
root@hpc ~ ✾ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.6 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.6"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.6 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.6"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.6"

When "manually" editing a file with a text editor like VIM, permissions are preserved as expected:

root@hpc ~ ✾ ls -alh /var/lib/warewulf/overlays/hosts/rootfs/etc/
total 4.0K
drwxr-xr-x. 2 root root  22 Sep  4 16:10 .
drwxr-xr-x. 3 root root  17 Jun 18 16:51 ..
-rw-r--r--. 1 root root 387 Sep  4 16:10 hosts.ww
root@hpc ~ ✾ vim /var/lib/warewulf/overlays/hosts/rootfs/etc/hosts.ww 
root@hpc ~ ✾ ls -alh /var/lib/warewulf/overlays/hosts/rootfs/etc/
total 4.0K
drwxr-xr-x. 2 root root  22 Sep  8 11:24 .
drwxr-xr-x. 3 root root  17 Jun 18 16:51 ..
-rw-r--r--. 1 root root 388 Sep  8 11:24 hosts.ww

However, when using wwctl to edit the file permissions are changed to 600 and must be changed back to fix the overlay.  I would not expect editing a file to change/break permissions.

root@hpc ~ ✾ wwctl overlay edit hosts /etc/hosts.ww 
root@hpc~ ✾ ls -alh /var/lib/warewulf/overlays/hosts/rootfs/etc/
total 4.0K
drwxr-xr-x. 2 root root  22 Sep  8 11:25 .
drwxr-xr-x. 3 root root  17 Jun 18 16:51 ..
-rw-------. 1 root root 387 Sep  8 11:25 hosts.ww
root@hpc ~ ✾ wwctl overlay chmod hosts /etc/hosts.ww 644
root@hpc~ ✾ ls -alh /var/lib/warewulf/overlays/hosts/rootfs/etc/
total 4.0K
drwxr-xr-x. 2 root root  22 Sep  8 11:25 .
drwxr-xr-x. 3 root root  17 Jun 18 16:51 ..
-rw-r--r--. 1 root root 387 Sep  8 11:25 hosts.ww

**Comment by anderbubble** [comment]
This was fixed in #1932 after a report in #1886. This fix was included in v4.6.2.

**Comment by conxuro** [comment]
This issue is still present in v4.7.0-1.

#1932 fixes the preservation of permissions from existing files but not with new files. With `wwctl overlay edit` new files are created always with 600 instead of umask or default permissions.

**Comment by anderbubble** [comment]
@conxuro thanks for reporting. Reopened.
